name: 02 - Workflow Events

on: 
  pull_request:
  workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event name: ${{ github.event_name }}"