name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/reach-app

        steps:
            - name: Checkout code
              uses: actions/Checkout/@v4

            - name: Setup Node
              uses: actions/setup-node@v3  

            - name: Install dependencies
              run: npm ci

            - name: Testing
              run: npm run test

            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"